# Pandas — Selectie en filtering

In deze notebook leer je de meest gebruikte technieken om rijen en kolommen te selecteren uit een DataFrame:

- Kolomselectie
- **Boolean filtering** — de primaire manier om rijen te filteren
- **`.loc[]`** en **`.iloc[]`** — voor label- en positie-gebaseerde selectie
- Sorteren en tellen

Alle technieken worden intensief gebruikt in de latere ML-notebooks.

In [1]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## Kolomselectie

In [2]:
# One column → Series
ages = titanic["age"]
print(type(ages))
ages.head()

<class 'pandas.core.series.Series'>

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [3]:
# Multiple columns → DataFrame (double square brackets)
selected = titanic[["survived", "pclass", "age", "fare"]]
selected.head()

   survived  pclass   age     fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

## Boolean filtering

Filtering werkt net als bij NumPy: je maakt een masker van `True`/`False`-waarden en past het toe op het DataFrame.

Combineer condities met:
- `&` (AND)
- `|` (OR)
- `~` (NOT)

⚠️ Zet elke conditie tussen haakjes wanneer je combineert.

In [4]:
# Simple condition
women = titanic[titanic["sex"] == "female"]
print(f"Number of women: {len(women)}")
women.head()

Number of women: 314

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [5]:
# Combine multiple conditions with &
first_class_survivors = titanic[(titanic["survived"] == 1) & (titanic["pclass"] == 1)]
print(f"First-class survivors: {len(first_class_survivors)}")

First-class survivors: 136

In [6]:
# Combine with | — passengers in 1st or 2nd class
first_or_second = titanic[(titanic["pclass"] == 1) | (titanic["pclass"] == 2)]
print(len(first_or_second))

# Alternative with .isin()
first_or_second_v2 = titanic[titanic["pclass"].isin([1, 2])]
print(len(first_or_second_v2))

400
400

In [7]:
# Comparison with numeric threshold
minors = titanic[titanic["age"] < 18]
print(f"Minors on board: {len(minors)}")

Minors on board: 113

## `.loc[]` — label-gebaseerde selectie

Met **`.loc[rows, columns]`** selecteer je op basis van **indexlabels** en **kolomnamen**.

In [8]:
# Select rows 5 through 9, columns 'survived', 'age' and 'sex'
titanic.loc[5:9, ["survived", "age", "sex"]]

   survived   age     sex
5         0   NaN    male
6         0  54.0    male
7         0   2.0    male
8         1  27.0  female
9         1  14.0  female

In [9]:
# .loc with boolean mask + column selection
# Returns surviving women with their age and class
titanic.loc[
    (titanic["survived"] == 1) & (titanic["sex"] == "female"), ["age", "pclass", "fare"]
].head()

    age  pclass     fare
1  38.0       1  71.2833
2  26.0       3   7.9250
3  35.0       1  53.1000
8  27.0       3  11.1333
9  14.0       2  30.0708

## `.iloc[]` — positie-gebaseerde selectie

Met **`.iloc[rows, columns]`** selecteer je op basis van **gehele getallen** (positie, 0-gebaseerd). Handig wanneer je de kolomnamen niet kent.

In [10]:
# First 5 rows, columns 0 through 3
titanic.iloc[0:5, 0:4]

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [11]:
# Last row
titanic.iloc[-1]

survived                0
pclass                  3
sex                  male
age                  32.0
sibsp                   0
parch                   0
fare                 7.75
embarked                Q
class               Third
who                   man
adult_male           True
deck                  NaN
embark_town    Queenstown
alive                  no
alone                True
Name: 890, dtype: object

## Sorteren

In [12]:
# Sort by one column (descending)
titanic.sort_values("fare", ascending=False).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False

In [13]:
# Sort by multiple columns
titanic.sort_values(["pclass", "fare"], ascending=[True, False]).head(8)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
341,1,1,female,24.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
311,1,1,female,18.0,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False

## Unieke waarden tellen

In [14]:
# Unique values in a column
print(titanic["pclass"].unique())
print(titanic["sex"].nunique(), "unique values in 'sex'")

[3 1 2]
2 unique values in 'sex'

In [15]:
# Count occurrences
print(titanic["pclass"].value_counts())
print()
# As proportions
print(titanic["survived"].value_counts(normalize=True).round(2))

pclass
3    491
1    216
2    184
Name: count, dtype: int64

survived
0    0.62
1    0.38
Name: proportion, dtype: float64

## Index resetten

Na filtering klopt de index van het resulterende DataFrame niet meer aaneengesloten. Gebruik `.reset_index(drop=True)` om de index opnieuw te nummeren.

In [16]:
women = titanic[titanic["sex"] == "female"].reset_index(drop=True)
print(women.index[:5].tolist())  # [0, 1, 2, 3, 4]

[0, 1, 2, 3, 4]

---

## Oefeningen

Gebruik de **Tips-dataset**: `tips = sns.load_dataset("tips")`.

In [17]:
tips = sns.load_dataset("tips")
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

**Oefening 1** — Selecteer alle rijen waar `sex == "Female"` én `smoker == "No"`. Hoeveel rijen zijn er?

In [18]:
# your solution here

**Oefening 2** — Gebruik `.isin()` om alle rijen te selecteren waar `day` gelijk is aan `"Sat"` of `"Sun"`. Bereken het gemiddelde fooi (`tip`) voor die rijen.

In [19]:
# your solution here

**Oefening 3** — Selecteer met `.loc[]` de kolommen `total_bill` en `tip` voor rijen 10 t/m 19. Bereken de fooi als percentage van de rekening voor die rijen en voeg het toe als nieuwe kolom.

In [20]:
# your solution here

**Oefening 4** — Gebruik `.value_counts()` om te bepalen: op welke dag van de week is er de meeste activiteit (meeste bezoeken)? En wat is de meest voorkomende partijgrootte (`size`)?

In [21]:
# your solution here

**Oefening 5** — Sorteer de tips-dataset op `total_bill` van hoog naar laag en selecteer de top-10. Wat zijn de gemiddelde fooi en het gemiddeld percentage bij de top-10?

In [22]:
# your solution here